### ISSUE TITLE
rose's Makefile.am was modified.

### ISSUE THREAD

**Issue by gleisonsdm** [chunhualiao/rose-apt-get#19]
Seems like rose does not generate binaries for tools by default using "make install-core".

That's the output for my binaries:
```bash
souzadinizme1@ip-172-31-35-240:~/workdir/rose-apt-get/rose-install/usr/rose/bin$ ls
libtool  rose-c++  rose-cc  rose-compiler  rose-config
```

@gleisonsdm : Try the process using make without flags, this should spend more time. If it spends a long time, find a way to compile the tools using make flags.

**Comment by chunhualiao** [comment]
try to type "make install" under bulidtree/
tools
tutorials

**Comment by gleisonsdm** [comment]
Works, but not produce all the tools we have.

I am testing "make install-tools" instead "make install-core" now, maybe users would like to have all tools ready to use using apt-get. What do you think about?

**Comment by chunhualiao** [comment]
just install as many as you can.

**Comment by gleisonsdm** [comment]
@chunhualiao : I have installed rose on my personal computer using the new PAA (It is working for me).
Please, try to install rose via command line when the time permits. You can find the instructions on the following link:

https://github.com/chunhualiao/rose-apt-get#using-the-ppa

Let me know any issues you have trying the described process.

**Comment by chunhualiao** [comment]
We now migrate to Ubuntu 18.
